name: PHP Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.1']
        composer-type: [stable, dev]

    name: PHP ${{ matrix.php-version }} & ${{ matrix.db-type }} & ${{ matrix.composer-type }}

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: tdc
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, apcu, pdo_sqlite, pdo_mysql, pdo_pgsql
          ini-values: apc.enable_cli = 1

      - name: Update composer
        run: composer self-update

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: |
          if [[ ${{ matrix.composer-type }} == 'stable' ]]; then
            composer update --prefer-dist --no-progress --no-suggest --prefer-stable
          else
            composer update --prefer-dist --no-progress --no-suggest
          fi

      - name: Run Sqlite tests
        run: composer sqlite
      - name: Run Mysql tests
        run: |
          sudo service mysql start && mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS tdc;';
          composer mysql
      - name: Run Postgres tests
        run: composer pgsql